# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'borked.io'
tagline:          'All things cloud and automation'
description:      'An IT engineerâ€™s insight on technologies, sometimes rambling thoughts, and journey throughout the world wide web.'
url:              'https://borked.io'
baseurl:          '/'
logo:             '/assets/logo.png'

encoding: UTF-8
excerpt_separator: <!--more-->

author:
  name:           'Rob Wolff'

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Sidebar link settings
sidebar_home_link:  true

google_analytics: UA-11095519-8

social:
  name: Rob Wolff
  links:
    - https://github.com/robwolff3
    - https://linkedin.com/in/rob-wolff-b4b8b537
